dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.flywaydb:flyway-core'
    runtimeOnly 'org.flywaydb:flyway-database-postgresql'
    runtimeOnly 'org.postgresql:postgresql'
    testImplementation 'org.testcontainers:postgresql:1.21.3'
    testImplementation 'org.testcontainers:junit-jupiter:1.21.3'
    testImplementation 'io.rest-assured:rest-assured:5.5.7'
    testImplementation 'com.tngtech.archunit:archunit-junit5:1.5.0'
    testImplementation 'io.swagger.parser.v3:swagger-parser:2.1.48'
}

sourceSets {
    test {
        resources {
            srcDir '../docs/openapi'
        }
    }
}

springBoot {
    mainClass = 'com.sanlam.claims.ClaimsServiceApplication'
}
